name: PyDSA CI/CD

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   name: Set up Python
                uses: actions/setup-python@v2
                with:
                    python-version: 3.12.0

            -   name: Install dependencies
                run: |
                    python -m pip install --upgrade pip
                    # python -m pip install -r .github/workflows/requirements.txt
                working-directory: ${{ github.workspace }}

            -   name: Build and deploy (if needed)
                run: |
                    # Add deployment commands here if you have a deployment process
