name: PyDSA CI/CD

on:
    push:
        branches:
            - main  # Adjust the branch name as needed
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   name: Set up Python
                uses: actions/setup-python@v2
                with:
                    python-version: 3.10  # Adjust Python version as needed

            -   name: Install dependencies
                run: |
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt

            -   name: Run tests
                run: pytest  # Adjust the test command based on your project structure and testing framework

            -   name: Lint code
                run: pylint .  # Adjust the linting command based on your project structure and linting tool

            -   name: Build and deploy (if needed)
                run: |
                    # Add deployment commands here if you have a deployment process

                # Example deployment to Heroku:
                #   heroku login -i
                #   git push heroku main
